name: Build Core Framework

on: [push]

env:
  nuGetVersionNumber: 4.5
  nuGetFullVersionNumber: 4.5.${{ github.run_number }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
    steps:
    - uses: actions/checkout@v1
    - name: Setup dotnet CLI
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.100
    - name: Prepare Legacy NuGet
      run: |
        cd .\.nuget
        ren NuGet.ex_ NuGet.exe
        cd ..
        .nuget\NuGet.exe restore Chinchilla.Logging.sln
    - name: Build with dotnet CLI
      run: dotnet build --configuration Release .\Chinchilla.Logging.sln
    - name: Pack with dotnet CLI
      run: |
        forfiles /s /m Chinchilla.Logging*.csproj /c "cmd /c dotnet pack @PATH -c Release -p:Version=${{ env.nuGetVersionNumber }} -p:PackageVersion=${{ env.nuGetFullVersionNumber }} --version-suffix beta-$(date +%Y%m%d%H%M%S) --include-symbols -p:SymbolPackageFormat=snupkg --include-source -o ../Packaged"
#    - name: Push with dotnet CLI
#      run: |
#        .nuget\NuGet.exe source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/cdmdotnet/index.json" -UserName cdmdotnet -Password ${{ secrets.GITHUB_TOKEN }}
#        dotnet nuget push Packaged\*.nupkg -s "GitHub"
